
- slurp:
    src: /etc/adjtime
  register: adjtime

- name: RTC UTC
  template:
    src: adjtime.j2
    dest: /etc/adjtime
  when: (adjtime.content | b64decode | split('\n'))[2] == "LOCAL"

- name: chronyd service
  systemd:
    name: "chronyd"
    state: "started"
    enabled: "yes"
