- name: firewalld service
  systemd:
    name: "firewalld"
    state: "started"
    enabled: "yes"

- name: Enable internal zone
  firewalld:
    interface: "{{ inside_nic }}"
    zone: internal
    state: enabled
    permanent: true
    immediate: true

- name: Enable external zone
  firewalld:
    interface: "{{ outside_nic }}"
    zone: external
    state: enabled
    permanent: true
    immediate: true
  when: outside_nic is defined

- name: Enable external masquerade
  firewalld:
    zone: external
    permanent: true
    immediate: true
    masquerade: true
    state: enabled
  when: outside_nic is defined

- name: Remove services in firewall external
  firewalld:
    service: "{{ item }}"
    state: disabled
    zone: external
    permanent: true
    immediate: true
  loop:
    - ssh
  when: outside_nic is defined

- name: Toggle services in firewall internal
  firewalld:
    service: "{{ item }}"
    state: "{{ local_ssh_access | default(false) | bool | ternary('disabled', 'enabled') }}"
    zone: internal
    permanent: true
    immediate: true
  loop:
    - ssh

- name: Create wlan zone
  firewalld:
    zone: wlan
    state: present
    permanent: true
  notify: reload-firewall
#  when: wlan_nic is defined

- name: Allow services in firewall
  firewalld:
    service: "{{ item.1 }}"
    state: enabled
    zone: "{{ item.0 }}"
    permanent: true
    immediate: true
  when: router_features_merged.internal_services_firewall is defined
  with_nested:
    - ['internal', 'wlan']
    - "{{ router_features_merged.internal_services_firewall }}"

# Policies
- name: policy_int_to_ext
  template:
    src: policy_int_to_ext.xml.j2
    dest: /etc/firewalld/policies/policy_int_to_ext.xml
  notify: reload-firewall
