---

- name: leases directory
  file:
    path: "{{ lease_dir }}/{{ group }}"
    state: directory

- find:
    paths: "{{ lease_dir }}/{{ group }}"
  register: lease_files

- slurp:
    src: "{{ item.path }}"
  loop: "{{ lease_files.files }}"
  register: lease_slurps

- set_fact:
    group_leases: []
- set_fact:
    dhcp_hosts: []

- name: List with map of 'host,mac' names and the lease IP value
  set_fact:
    group_leases: "{{ group_leases + [{'name': item.item.path | basename(), 'value': item.content | b64decode }] }}"
  loop: "{{ lease_slurps.results  }}"

- set_fact:
    dhcp_pool: "{{ query('sequence', dhcp_range) }}"
  vars:
    start: "{{ ip_start }}"
    end: "{{ ip_end }}"
    dhcp_range: "start={{ start }} end={{ end }}"

- set_fact:
    dhcp_pool_free: "{{ dhcp_pool | difference(group_leases | map(attribute='value')) }}"

- name: List of 'host,mac' items desired based on inventory group
  set_fact:
    dhcp_hosts: "{{ dhcp_hosts + [item + ',' + hostvars[item].mac] }}"
  loop: "{{ groups[group] }}"
  when: groups[group] is defined

- name: Add leases from free pool for hosts not already in leases directory
  set_fact:
    group_leases: "{{ group_leases + [{'name': item, 'value': dhcp_pool_free[idx] }] }}"
  loop: "{{ dhcp_hosts | difference(group_leases | map(attribute='name')) }}"
  loop_control:
    index_var: idx

- name: Delete lease files not in desired list
  file:
    path: "{{ lease_dir }}/{{ group }}/{{ item.name }}"
    state: absent
  loop: "{{ group_leases }}"
  when: item.name is not in dhcp_hosts

- name: Write lease files
  copy:
    dest: "{{ lease_dir }}/{{ group }}/{{ item.name }}"
    content: "{{ item.value }}"
  loop: "{{ group_leases }}"
  when: item.name is in dhcp_hosts

- name: Store group leases fact
  set_fact:
    leases: "{{leases | combine({group: group_leases})}}"
