---
- include_vars: main.yml

- name: Install packages
  dnf:
    name: "
      dnsmasq,
      python-firewall,
      firewalld
      "
    state: present

- name: hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  register: hosts_conf

- include_tasks: firewall.yml
- include_tasks: dnsmasq.yml
