# DHCP clients DNS and IP reservation
dhcp_reservations:
  lan_hosts:
    - name: wlan-ap-1
      mac: 'b8:..'
    - name: switch-1
      mac: 'd8:..'

inside_nic: eth1
router_features:
  dhcpd:
    enabled: true
    router: 192.168.0.1

firewalld:
  enabled: true
  zones:
    - name: internal
      interface: "{{ inside_nic }}"
      service_allow:
        - 'dns'
        - 'dhcp'
      service_remove: []

network:
  network_manager_resolved_disable: true
  no_auto_default:
    - eth0
    - "{{ inside_nic }}"
  dns_servers:
    - '192.168.0.2'
    - '1.1.1.1'
    - '8.8.8.8'
  connections:
    - id: internal
      interface_name: "{{ inside_nic }}"
      zone: internal
      ipv4:
        static_ip: true
    - id: cloud-init eth0
      file: cloud-init-eth0
      suppress_reload: true
      interface_name: eth0
      ipv4:
        ignore_auto_routes: true
