vms: []
vm_data: {}
vm_data_path: "{{ data0_path }}"
vm_volume_group: "{{ data_vg }}"
create_vms: []
updated_vms: []
vmfs_current: []
vmfs_desired: []
vm_networks: []
vm_inventory: {}
create_networks: []
vm_mounts_current: []
vm_mounts_desired: []
