- rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: RPMfusion
  dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Configure rpmfusion repositories
  ini_file:
    dest: "/etc/yum.repos.d/{{ item.0.name }}.repo"
    section: "{{ item.0.section }}"
    option: "{{ item.1.option }}"
    value: "{{ item.1.value }}"
    no_extra_spaces: true
    create: false
  with_nested:
    - [
      {name: rpmfusion-free, section: rpmfusion-free},
      {name: rpmfusion-free-updates, section: rpmfusion-free-updates}
    ]
    - [
      {option: "enabled", value: "1"},
      {option: "excludepkgs", value: "{{ use_dnf_staging | ternary('*', '') }}"},
    ]

# is package installed?
- package_facts:
    manager: rpm

- name: rpmfusion multimedia group will pull in ffmpeg
  shell: dnf -y swap ffmpeg-free ffmpeg --allowerasing
  when: "'ffmpeg-free' in ansible_facts.packages"

- name: workstation release identify
  shell: dnf -y swap fedora-release-identity-cloud fedora-release-identity-workstation
  when: "'fedora-release-identity-cloud' in ansible_facts.packages"

- name: jack-audio-connection-kit swap
  shell: dnf -y swap jack-audio-connection-kit pipewire-jack-audio-connection-kit-libs
  when: "'jack-audio-connection-kit' in ansible_facts.packages"

- name: Remove installer packages
  shell: dnf -y remove anaconda*
  when: "'anaconda' in ansible_facts.packages"

- name: Add packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - libreoffice-x11 # Avoid KDE framework

- name: Remove packages
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - libreoffice-kf5 # Avoid KDE framework

- name: Install workstation packages
  dnf:
    name: "{{ workstation_packages | join(',') }}"
    state: present

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
