all:
  children:
    homelab:
      children:
        servers:
        vms:

    # Physical servers
    servers:
      hosts:
        myserver:
          ansible_host: <static IP>
          data_dev: /dev/disk/by-id/xxxx
          data0_lv_size: 45%VG
          inside_nic: br0
          outside_nic: enp6s0
#          router_features:
#            dhcpd:
#              enabled: false
#          vm_volume_group: SSD
#          vm_data_path: /var/local

    # DHCP clients DNS and IP reservation
    lan_hosts:
      hosts:
        hephaestus:
          mac: '3c:7c:3f:2e:80:fc'

    # Host from servers group with router role
    routers:
      hosts:
        myserver:

    # Host from servers group with fileserver role
    fileservers:
      hosts:
        myserver:

    # Host from servers group with vm-host role
    vm_hosts:
      hosts:
        myserver:

    # Runtime groups used by vm-inventory
    staging_vms:
    vms:

    # Group membership for enabling test updates
    staging:
      children:
        staging_vms:
