- file:
    path: "{{ vmfs_path }}"
    state: directory

- name: mount vmfs volume
  mount:
    name: "{{ vmfs_path }}"
    src: vmfs
    state: mounted
    fstype: "virtiofs"

# Virtiofs doesn't play well with selinux.
# Update: fixed with  <binary path='/usr/libexec/virtiofsd' xattr='on'>
- name: Put SELinux in desired mode
  selinux:
    policy: targeted
    state: enforcing
