vm_image:
  f39: Fedora-Cloud-Base-39-1.5.x86_64.raw.xz

# States:
# created, running, shutdown, destroyed
vms:
  - name: test-1
    state: running
    image: f39
    host: myserver
    disk: 10
    admin_network: true
    delete_on_termination: true
