
- set_fact:
    vm_mounts_current: "{{ vm_mounts_current + [{'vm': vm.name, 'source': item.source['@dev'], 'target': item.target['@dev']}] }}"
  with_items:
    - "{{ vars['dom_dict_' + vm.name | replace('-', '_')].domain.devices.disk }}"
  when: item.source['@dev'] is defined
