- name: Inventory existing VMs with admin IP address from status json
  debug:
    msg: "VM: {{ item.name }}, JSON: {{ vm_admin_network_status_json.content | b64decode | from_json }}"
- set_fact:
    vm_inventory: "{{ vm_inventory | combine({item.name: {'address': ip } | combine(vm_inventory[item.name]) }) }}"
  vars:
    mac: "{{ vm_inventory[item.name].mac[vm_admin_network_name] }}"
    query: "[?\"mac-address\"=='{{ mac }}'].\"ip-address\""
    json: "{{ vm_admin_network_status_json.content | b64decode | from_json }}"
    ip: "{{ json | json_query(query) | first }}"
  when: (vm_admin_network_status_json.content | b64decode | from_json) != []