- name: Inventory existing VMs with admin IP address from status json
  set_fact:
    vm_inventory: "{{ vm_inventory | combine({item.vm.name: {'address': ip } | combine(vm_inventory[item.vm.name]) }) }}"
  vars:
    mac: "{{ vm_inventory[item.vm.name].mac }}"
    query: "[?\"mac-address\"=='{{ mac }}'].\"ip-address\""
    json: "{{ vm_admin_network_status_json.content | b64decode | from_json }}"
    ip: "{{ json | json_query(query) | first }}"