
- name: List available networks
  virt_net:
    command: list_nets
  register: list_nets

- name: Define bridge network
  virt_net:
    command: define
    name: "{{ vm_network_bridge_name }}"
    xml: "{{ lookup('template', 'network-bridge.xml.j2') }}"
  when:
    - network_bridge_name is defined
    - vm_network_bridge_name not in list_nets

- name: Ensure that bridge network will be started at boot
  virt_net:
    autostart: yes
    name: "{{ vm_network_bridge_name }}"

- name: Ensure that a given network is active
  virt_net:
    state: active
    name: "{{ vm_network_bridge_name }}"
