- file:
    path: "{{ data0_path }}/vmfs"
    state: directory

- include_tasks: get-vmfs.yml
  with_dict:
    - "{{ vm_inventory }}"
  loop_control:
    loop_var: vm

- name: Generate VMFS XML definition
  template:
    src: "virtiofs.xml.j2"
    dest: "{{ data0_path }}/vmhost/vmfs.xml"

- set_fact:
    vmfs_desired: "{{ vmfs_desired + [{'vm': vm.value.name, 'source': data0_path + '/vmfs', 'target': 'vmfs' }] }}"
  with_dict:
    - "{{ vm_inventory }}"
  loop_control:
    loop_var: vm

- debug:
    msg: "{{vmfs_desired}}"

- debug:
    msg: "{{vmfs_current}}"
- command: /usr/bin/virsh attach-device --persistent {{ item.vm }} {{ data0_path }}/vmhost/vmfs.xml
  with_items: "{{ vmfs_desired|difference(vmfs_current) }}"
