---

- name: dnsmasq restart
  systemd: name=dnsmasq state=restarted

- name: systemd resolved restart
  systemd: name=systemd-resolved state=restarted

- name: reload-firewall
  command: firewall-cmd --reload
