vm_image:
  f39: Fedora-Cloud-Base-39-1.5.x86_64.raw.xz

# States:
# created, running, shutdown, destroyed
vms:
  - name: router-1
    # Set hostname from user-data instead of dhcp
    static_hostname: true
    # Set static IP
    static_ip: 192.168.0.2/24
    inventory_groups:
      - vm_routers
    state: running
    image: f39
    host: myserver
    disk: 10
    admin_network: true
    bridge_network: true
    delete_on_termination: false
