- name: Install packages
  dnf:
    name: "
      libvirt-daemon-kvm
      "
    state: present

- name: libvirt-daemon
  systemd:
    name: libvirtd
    enabled: yes

# Non-root libvirt connection
- name: libvirt group membership
  user: name="{{ owner }}"
    groups="libvirt"
    append="yes"

# Non-root libvirt connection
- name: Socket ownership
  lineinfile:
    dest: "/etc/libvirt/libvirtd.conf"
    regexp: "unix_sock_group = "
    line: 'unix_sock_group = "libvirt"'
  notify: libvirtd

# Non-root libvirt connection
- name: Socket ownership
  lineinfile:
    dest: "/etc/libvirt/libvirtd.conf"
    regexp: "unix_sock_rw_perms = "
    line: 'unix_sock_rw_perms = "0770"'
  notify: libvirtd
