- name: Stat resolv.conf
  stat: path=/etc/resolv.conf
  register: resolv_conf

- name: Remove resolv.conf if symlink
  file:
    path: /etc/resolv.conf
    state: absent
  when:
    - resolv_conf.stat.islnk|default(false) == true

- name: resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Network manager config file
  template:
    src: networkmanager.conf.j2
    # Not working for some reason
    #dest: /etc/NetworkManager/conf.d/ansible-network.conf
    dest: /etc/NetworkManager/NetworkManager.conf
  notify: nm-restart

- name: resolved service
  systemd:
    name: "systemd-resolved"
    state: "stopped"
    enabled: "no"
    masked: "yes"
