lease_dir: "/var/local/ansible-dnsmasq"
dnsmasq_state_needed: started
leases: {}
lan_ip_start: 5
lan_ip_end: 50
vm_ip_start: 151
vm_ip_end: 254
wlan_ip_start: 5
wlan_ip_end: 50
dhcp_hosts: []
group_leases: []
