- name: Install packages
  dnf:
    name: "
      podman
      "
    state: present

- name: Containers that should be present for current host
  set_fact:
    ctr_dict: "{{ ctr_dict | combine({item.name: item }) }}"
  with_items: "{{ containers }}"
  when:
    - item.host == inventory_hostname

- include_tasks: vmfs.yml
- include_tasks: volume-templates.yml
#- include_tasks: ports.yml
- include_tasks: containers.yml
- include_tasks: dnsmasq-templates.yml
