- name: Generate volumes list
  set_fact:
    volumes_list: "{{ volumes_list | combine({item.0.name: volumes_list[item.0.name] | default([]) + [mount_path + ':' + item.1.path + ':z'] }) }}"
  loop: "{{ ctr_dict | subelements('volumes', skip_missing=True) }}"
  vars:
    mount_path: "{{ [vmfs_path, item.1.name, item.1.subdir|default('')] | join('/') }}"
  when:
    - item.1.type == "vmfs"
    - item.1.name is in vmfs

- name: container VMFS directories
  file:
    path: "{{ mount_path }}"
    owner: "{{ item.0.user if item.0.user is defined else omit }}"
    state: directory
    mode: "{{ item.1.mode if item.1.mode is defined else omit }}"
  loop: "{{ ctr_dict | subelements('volumes', skip_missing=True) }}"
  vars:
    mount_path: "{{ [vmfs_path, item.1.name, item.1.subdir|default('')] | join('/') }}"
  when:
    - item.1.type == "vmfs"
    - item.1.name is in vmfs
