- name: Enable internal zone
  firewalld:
    interface: "{{ inside_nic }}"
    zone: internal
    state: enabled
    permanent: true
    immediate: true

- name: Enable external zone
  firewalld:
    interface: "{{ outside_nic }}"
    zone: external
    state: enabled
    permanent: true
    immediate: true
  when: outside_nic is defined

- name: Remove services in firewall external
  firewalld:
    service: "{{ item }}"
    state: disabled
    zone: external
    permanent: true
    immediate: true
  loop:
    - ssh
  when: outside_nic is defined

- name: Create wlan zone
  firewalld:
    zone: wlan
    state: present
    permanent: true
  register: wlan_zone
  when: wlan_nic is defined

- name: Reload firewall to enable wlan zone
  command: firewall-cmd --reload
  when: wlan_zone.changed

- name: Allow services in firewall
  firewalld:
    service: "{{ item.1 }}"
    state: enabled
    zone: "{{ item.0 }}"
    permanent: true
    immediate: true
  with_nested:
    - ['internal', 'wlan']
    - "{{ router_features_merged.internal_services_firewall }}"
