- hosts: vm_hosts
  become: True
  tasks:
    - include_role:
        name: vm-host
        tasks_from: inventory

- hosts: "{{ staging | default(false) | bool | ternary('staging_container_hosts', 'container_hosts') }}"
  become: True
  roles:
    - container-host

- hosts: routers
  become: True
  tasks:
    - set_fact:
        dnsmasq_containers_conf: "{{ dnsmasq_containers_conf | default('') + hostvars[item].dnsmasq_conf | default('') }}"
      with_items: "{{ groups['container_hosts'] }}"
    - include_role:
        name: router
        tasks_from: update-dnsmasq
      when: staging | default(false) | bool is false
