- hosts: servers
  become: True
  tasks:
    - dnf:
        list: updates
      register: list_updates
    - debug: msg="{{ list_updates }}"
    - systemd:
        name: "{{ item }}"
        state: stopped
      when: list_updates.results | length > 0
      with_items:
        - libvirt-guests
        - smb
    - include_tasks: library/updatereboot.yml
