---
- set_fact:
    stored_group_leases: []
    group_leases: []
    dhcp_hosts: []

- name: leases directory
  file:
    path: "{{ leases_dir }}/{{ reservations | default(group) }}"
    state: directory

- find:
    paths: "{{ leases_dir }}/{{ reservations | default(group) }}"
  register: lease_files

- slurp:
    src: "{{ item.path }}"
  loop: "{{ lease_files.files }}"
  register: lease_slurps

- name: List of 'host,mac' items desired based on inventory group
  set_fact:
    dhcp_hosts: "{{ dhcp_hosts + [item + ',' + hostvars[item].dhcp_mac] }}"
  loop: "{{ groups[group] }}"
  when:
    - group is defined
    - groups[group] is defined
    - hostvars[item].static_ip is not defined
    - hostvars[item].dhcp_mac is defined

- name: List of 'host,mac' items desired based on reservations
  set_fact:
    dhcp_hosts: "{{ dhcp_hosts + [item.name + ',' + item.mac] }}"
  loop: "{{ dhcp_reservations[reservations] }}"
  when:
    - reservations is defined
    - dhcp_reservations[reservations] is defined

- name: Read stored leases list with map of 'host,mac' names and the lease IP value
  set_fact:
    stored_group_leases: "{{ stored_group_leases + [{'name': item.item.path | basename(), 'value': item.content | b64decode }] }}"
  loop: "{{ lease_slurps.results  }}"

- name: Import eIP list with map of 'host,mac' names and the lease IP value
  set_fact:
    group_leases: "{{ group_leases + [{'name': item + ',' + hostvars[item].dhcp_mac, 'value': hostvars[item].eip }] }}"
  loop: "{{ groups[group] }}"
  when:
    - group is defined
    - groups[group] is defined
    - hostvars[item].eip is defined
    - hostvars[item].dhcp_mac is defined

- name: Import leases desired from stored leases
  set_fact:
    group_leases: "{{ group_leases + [item] }}"
  loop: "{{ stored_group_leases }}"
  when:
    - item.name is in dhcp_hosts
    - item.name is not in (group_leases | map(attribute='name'))
    # eIPs only taken from inventory. Not stored values
    - item.value is not in (group_leases | map(attribute='value'))

- set_fact:
    dhcp_pool: "{{ query('sequence', dhcp_range) }}"
  vars:
    start: "{{ ip_start }}"
    end: "{{ ip_end }}"
    dhcp_range: "start={{ start }} end={{ end }}"

- set_fact:
    dhcp_pool_free: "{{ dhcp_pool | difference(group_leases | map(attribute='value')) }}"

- name: Add leases from free pool for hosts not already in leases
  set_fact:
    group_leases: "{{ group_leases + [{'name': item, 'value': dhcp_pool_free[idx] }] }}"
  loop: "{{ dhcp_hosts | difference(group_leases | map(attribute='name')) }}"
  loop_control:
    index_var: idx

- name: Delete lease files not in desired list
  file:
    path: "{{ leases_dir }}/{{ reservations | default(group) }}/{{ item.name }}"
    state: absent
  loop: "{{ stored_group_leases }}"
  when: item.name is not in dhcp_hosts

- name: Write lease files
  copy:
    dest: "{{ leases_dir }}/{{ reservations | default(group) }}/{{ item.name }}"
    content: "{{ item.value }}"
  loop: "{{ group_leases }}"

- name: Store group leases fact
  set_fact:
    leases: "{{leases | combine({reservations | default(group): group_leases})}}"
