# Mount VMFS in base role to be available for dnf repo
- name: VMFS directories
  file:
    path: "{{ vmfs_path }}/{{ item }}"
    state: directory
  with_items: "{{ vmfs }}"
  when:
    - vmfs is defined
    - vmfs_path is defined

- name: mount vmfs volume
  mount:
    name: "{{ vmfs_path }}/{{ item }}"
    src: "{{ item }}"
    state: mounted
    fstype: "virtiofs"
    opts: 'defaults'
  with_items: "{{ vmfs }}"
  when:
    - vmfs is defined
    - vmfs_path is defined

- name: Toggle testing repo
  ini_file:
    dest: "/etc/yum.repos.d/fedora-updates-testing.repo"
    section: "updates-testing"
    option: "enabled"
    value: "{{ updates_testing_enabled | ternary('1', '0') }}"
    no_extra_spaces: true

- name: Cache packages
  ini_file:
    dest: "/etc/yum.repos.d/fedora.repo"
    section: "fedora"
    option: "keepcache"
    value: "1"
    no_extra_spaces: true
  when: dnf_keepcache_enabled

- name: Cache updates
  ini_file:
    dest: "/etc/yum.repos.d/fedora-updates.repo"
    section: "updates"
    option: "keepcache"
    value: "1"
    no_extra_spaces: true
  when: dnf_keepcache_enabled

- name: Configure fedora repo
  ini_file:
    dest: "/etc/yum.repos.d/fedora.repo"
    section: "fedora"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_items:
    - option: "enabled"
      value: "1"
    - option: "deltarpm"
      value: "{{ dnf_keepcache_enabled | ternary('0', '1') }}"

- name: Configure fedora updates repo
  ini_file:
    dest: "/etc/yum.repos.d/fedora-updates.repo"
    section: "updates"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_items:
    - option: "enabled"
      value: "{{ use_dnf_staging | ternary('0', '1') }}"
    - option: "deltarpm"
      value: "{{ dnf_keepcache_enabled | ternary('0', '1') }}"

- name: Create local repositories
  template:
    src: "{{ dnf_repositories[item].template }}"
    dest: /etc/yum.repos.d/{{ dnf_repositories[item].name }}.repo
  with_items: "{{ dnf_repositories_create }}"

- name: Toggle local repositories
  ini_file:
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
    section: "{{ item.section }}"
    option: "enabled"
    value: "{{ item.enabled }}"
    no_extra_spaces: true
    create: false
  with_items: "{{ dnf_repositories_toggle }}"

- name: Inotify watches increase
  sysctl:
    name: fs.inotify.max_user_watches
    value: "204800"

- name: SSH key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ssh_public_key }}"
  when: ansible_user is defined

- name: Machine info
  template:
    src: machine-info.j2
    dest: /etc/machine-info
  when: chassis is defined

#- debug:
#    msg: "{{ ansible_devices }}"

- name: sudo admin
  template:
    src: sudo_admin.j2
    dest: /etc/sudoers.d/ansible_admin
  when: sudo_admin

- include_tasks: timedate.yml
