- include_tasks: "packages-{{ ansible_distribution_major_version }}.yml"

# Mount VMFS in base role to be available for dnf repo
- name: VMFS directories
  file:
    path: "{{ vmfs_path }}/{{ item }}"
    state: directory
  with_items: "{{ vmfs }}"
  when:
    - vmfs is defined
    - vmfs_path is defined

- name: mount vmfs volume
  mount:
    name: "{{ vmfs_path }}/{{ item }}"
    src: "{{ item }}"
    state: mounted
    fstype: "virtiofs"
    opts: 'defaults'
  with_items: "{{ vmfs }}"
  when:
    - vmfs is defined
    - vmfs_path is defined

- name: Toggle testing repo
  ini_file:
    dest: "/etc/yum.repos.d/fedora-updates-testing.repo"
    section: "updates-testing"
    option: "enabled"
    value: "{{ updates_testing_enabled | ternary('1', '0') }}"
    no_extra_spaces: true
    create: false

- name: Toggle repo cache
  ini_file:
    dest: "/etc/dnf/dnf.conf"
    section: "main"
    option: "keepcache"
    value: "{{ dnf_keepcache_enabled | ternary('1', '0') }}"
    no_extra_spaces: true
    create: false

- name: Configure fedora repositories
  ini_file:
    dest: "/etc/yum.repos.d/{{ item.0.name }}.repo"
    section: "{{ item.0.section }}"
    option: "{{ item.1.option }}"
    value: "{{ item.1.value }}"
    no_extra_spaces: true
    create: false
  with_nested:
    - [
      {name: fedora, section: fedora},
      {name: fedora-updates, section: updates}
    ]
    - [
      {option: "enabled", value: "1"},
      {option: "excludepkgs", value: "{{ use_dnf_staging | ternary('*', '') }}"},
    ]

- name: Create local repositories
  template:
    src: "{{ dnf_repositories[item].template }}"
    dest: /etc/yum.repos.d/{{ dnf_repositories[item].name }}.repo
  with_items: "{{ dnf_repositories_create }}"

- name: Inotify watches increase
  sysctl:
    name: fs.inotify.max_user_watches
    value: "204800"

- name: Machine info
  template:
    src: machine-info.j2
    dest: /etc/machine-info
  when: chassis is defined

#- debug:
#    msg: "{{ ansible_devices }}"

- include_tasks: timedate.yml
