# workaround for power button to shut down machine
#chassis: vm
sudo_admin: true
vm_networks:
  - name: host-bridge
vm_images: "{{ data0_path }}/share/Linux-images"

vm_image:
  f36: Fedora-Cloud-Base-36-1.5.x86_64.raw.xz

#vm_data:
#  data1:
#    name: data1
#    size: 10
#    host: myserver
#    vm: vm1
#    device: vdb

# States:
# running, shutdown, destroyed
vms:
  - name: staging1
    hostname: vm-staging1
    inventory_groups:
      - staging_vms
    state: running
    image: f36
    host: myserver
    disk: 10
    network: host-bridge
    delete_on_termination: true
    serial: 1

  - name: vm1
    state: running
    image: f36
    host: myserver
    disk: 50
    network: host-bridge
    delete_on_termination: false
    serial: 1
