# Fetch VM inventory and VMs to be created.
- hosts: vm_hosts
  become: True
  tasks:
    - include_role:
        name: vm-host
        tasks_from: inventory

# Update Dnsmasq from inventory
- hosts: routers
  become: True
  tasks:
    - include_role:
        name: router
        tasks_from: update-dnsmasq

# Perform VM setup
- hosts: vm_hosts
  become: True
  roles:
    - vm-host
