---

- include_tasks: firewall.yml

- name: Install packages
  dnf:
    name: "
      dnsmasq
      "
    state: present
  register: dnsmasq_pkg

- include_tasks: get-leases.yml
  vars:
    group: lan_hosts
    ip_start: "{{ lan_ip_start }}"
    ip_end: "{{ lan_ip_end }}"

- include_tasks: get-leases.yml
  vars:
    group: wlan_hosts
    ip_start: "{{ wlan_ip_start }}"
    ip_end: "{{ wlan_ip_end }}"
  when: wlan_nic is defined

- name: dnsmasq main conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  register: dnsmasq_conf

- name: unit override directory
  file:
    path: /etc/systemd/system/dnsmasq.service.d
    state: directory

- name: unit override conf
  template:
    src: unit-override.conf.j2
    dest: /etc/systemd/system/dnsmasq.service.d/unit-override.conf
  register: unit_conf

- name: hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  register: hosts_conf

- name: dnsmasq service state needed
  set_fact:
    dnsmasq_state_needed: restarted
  when: dnsmasq_conf.changed
      or hosts_conf.changed
      or unit_conf.changed

- name: dnsmasq service
  systemd:
    name: "dnsmasq"
    state: "{{ dnsmasq_state_needed}}"
    enabled: "yes"
    daemon_reload: "yes"

- name: dispatcher
  template:
    src: dnsmasq-dispatcher.sh.j2
    dest: /etc/NetworkManager/dispatcher.d/dnsmasq-dispatcher.sh
    owner: root
    group: root
    mode: "0700"

- name: systemd resolved config
  template:
    src: systemd-resolved.j2
    dest: /etc/systemd/resolved.conf
  notify: systemd resolved restart
