---

- include_tasks: get-leases.yml
  vars:
    group: vms
    ip_start: "{{ vm_ip_start }}"
    ip_end: "{{ vm_ip_end }}"

- name: dnsmasq vms conf
  template:
    src: dnsmasq-vms.conf.j2
    dest: /etc/dnsmasq.d/vms.conf
  notify: dnsmasq restart

- name: dnsmasq container directives
  copy:
    content: "{{ dnsmasq_containers_conf }}"
    dest: /etc/dnsmasq.d/containers.conf
  notify: dnsmasq restart
  when: dnsmasq_containers_conf is defined
